sudo: required
language: node_js
node_js:
  - --lts
cache: skip
services:
  - docker
env:
  matrix:
    - CONTAINER=ksiig/node-jtr
before_install:
  - docker pull $CONTAINER
install:
  - docker run -v $(pwd):/app $CONTAINER bash -c "cd app && yarn install"
script:
  - docker run -v $(pwd):/app $CONTAINER bash -c "cd app && yarn build"
  - docker run -v $(pwd):/app $CONTAINER bash -c "cd app && yarn lint"
  - docker run -v $(pwd):/app $CONTAINER bash -c "cd app && yarn test"
  - yarn codecov
